# Generated by Django 4.1.7 on 2023-02-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerpath', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='user_courses', to='careerpath.course'),
        ),
    ]
