# Generated by Django 4.1.7 on 2023-02-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerpath', '0004_remove_user_courses_user_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_courses',
        ),
    ]
